export const USER_LOGOUT = "USER_LOGOUT";
export const APP_SET_USER_DETAILS = "APP_SET_USER_DETAILS";
export const LOGIN_SET_CHECKED = "LOGIN_SET_CHECKED";
export const APP_SET_TOKEN = "APP_SET_TOKEN";
export const APP_SET_INITIALIZING = "APP_SET_INITIALIZING";
